=== djordjee55/xml-veb-servisi/KT2/potvrda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://www.xws.org/potvrda"
    xmlns:potvrda="http://www.xws.org/potvrda">

    <xs:element name="Potvrda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Qr_kod" type="xs:string"/>
                <xs:element name="Primalac" type="potvrda:TLice"/>
                <xs:element name="Doze" type="potvrda:TVakcinacija"/>
                <xs:element name="Zdravstvena_ustanova" type="xs:string"/>
                <xs:element name="Datum_izdavanja" type="xs:date"/>
            </xs:sequence>
            <xs:attribute name="sifra" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TLice">
        <xs:sequence>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element name="Pol" type="xs:string"/>
            <xs:element name="Datum_rodjenja" type="xs:date"/>
            <xs:element name="JMBG">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVakcinacija">
        <xs:sequence>
            <xs:element form="qualified" maxOccurs="unbounded" name="Doza" type="potvrda:TDoza"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TDoza">
        <xs:sequence>
            <xs:element name="Ustanova" type="xs:string"/>
            <xs:element name="Naziv" type="xs:string"/>
            <xs:element name="Datum_davanja" type="xs:date"/>
            <xs:element name="Broj_serije" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="redni_broj" type="xs:positiveInteger" default="1"> </xs:attribute>
    </xs:complexType>
</xs:schema>

=== djordjee55/xml-veb-servisi/KT2/instanca_potvrde.xml
<?xml version="1.0" encoding="UTF-8"?>
<Potvrda xmlns="http://www.xws.org/potvrda"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xws.org/potvrda potvrda.xsd">
    <Qr_kod>url na koji treba da vodi qr kod</Qr_kod>
    <Primalac>
        <Ime>Marko</Ime>
        <Prezime>Marković</Prezime>
        <Pol>Muško</Pol>
        <Datum_rodjenja>1987-05-23</Datum_rodjenja>
        <JMBG>1233242343214</JMBG>
    </Primalac>
    <Doze>
        <Doza redni_broj="1">
            <Ustanova>Klinički centar Zvezdara</Ustanova>
            <Naziv>Pfizer</Naziv>
            <Datum_davanja>2021-08-20</Datum_davanja>
            <Broj_serije>234453</Broj_serije>
        </Doza>
    </Doze>
    <Zdravstvena_ustanova>Klinički centar Zvezdara</Zdravstvena_ustanova>
    <Datum_izdavanja>2021-09-20</Datum_izdavanja>
</Potvrda>

=== djordjee55/xml-veb-servisi/vaccination-main/src/main/resources/static/xml/potvrda.xml
<?xml version="1.0" encoding="UTF-8"?>
<Potvrda xmlns:tip="http://www.xws.org/tipovi"
         xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
         xmlns="http://www.xws.org/potvrda"
         xmlns:pred="http://www.xws.org/predicate"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.xws.org/potvrda file:../xsd/potvrda.xsd"
         id="b9b1ba65-b61d-443d-9b4a-4b029c427b93"
         about="http://www.xws.org/potvrda#b9b1ba65-b61d-443d-9b4a-4b029c427b93">
    <Datum_izdavanja property="pred:datumIzdavanja" datatype="xs:date">2006-05-04</Datum_izdavanja>
    <Qr_kod>Qr_kod0</Qr_kod>
    <Primalac>
        <tip:Ime>Ime0</tip:Ime>
        <tip:Prezime>Prezime0</tip:Prezime>
        <tip:Datum_rodjenja>2006-05-04</tip:Datum_rodjenja>
        <tip:Pol>M</tip:Pol>
        <tip:JMBG rel="pred:identifikatorKorisnika" href="http://www.xws.org/korisnici#921909aa-8ff1-47f4-b761-4cbac06929ad">0000000000000</tip:JMBG>
    </Primalac>
    <Doze>
        <Doza>
            <Tip_vakcine property="pred:nazivVakcine" datatype="xs:string">Pfizer-BioNTech</Tip_vakcine>
            <Datum_davanja property="pred:datumVakcinisanja" datatype="xs:date">2006-05-04</Datum_davanja>
            <Broj_serije>Broj_serije0</Broj_serije>
            <Redni_broj property="pred:brojVakcine" datatype="xs:positiveInteger">50</Redni_broj>
        </Doza>
        <Doza>
            <Tip_vakcine property="pred:nazivVakcine" datatype="xs:string">Pfizer-BioNTech</Tip_vakcine>
            <Datum_davanja property="pred:datumVakcinisanja" datatype="xs:date">2006-05-04</Datum_davanja>
            <Broj_serije>Broj_serije1</Broj_serije>
            <Redni_broj property="pred:brojVakcine" datatype="xs:positiveInteger">50</Redni_broj>
        </Doza>
    </Doze>
    <Zdravstvena_ustanova>Zdravstvena_ustanova0</Zdravstvena_ustanova>
</Potvrda>

=== djordjee55/xml-veb-servisi/src/main/resources/static/xml/potvrda.xml
<?xml version="1.0" encoding="UTF-8"?>
<Potvrda xmlns="http://www.xws.org/potvrda"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xws.org/potvrda ../xsd/potvrda.xsd">
    <Qr_kod>sadasfds</Qr_kod>
    <Primalac>
        <Ime xmlns="http://www.xws.org/tipovi">Njegos</Ime>
        <Prezime xmlns="http://www.xws.org/tipovi">Blagojevic</Prezime>
        <Datum_rodjenja xmlns="http://www.xws.org/tipovi">2021-12-20</Datum_rodjenja>
        <Pol xmlns="http://www.xws.org/tipovi">M</Pol>
        <JMBG xmlns="http://www.xws.org/tipovi">2904999183925</JMBG>
    </Primalac>
    <Doze>
        <Doza>
            <Tip_vakcine>Pfizer-BioNTech</Tip_vakcine>
            <Datum_davanja>2021-12-20</Datum_davanja>
            <Broj_serije></Broj_serije>
        </Doza>
    </Doze>
    <Zdravstvena_ustanova>Zvezdara</Zdravstvena_ustanova>
    <Datum_izdavanja>2021-12-21</Datum_izdavanja>
</Potvrda>
