=== djordjee55/xml-veb-servisi/KT2/saglasnost.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://www.xws.org/saglasnost"
    xmlns:saglasnost="http://www.xws.org/saglasnost">

    <xs:element name="Saglasnost">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pacijent" type="saglasnost:TLice"> </xs:element>
                <xs:element name="Datum" type="xs:date"/>
                <xs:element name="Evidencija_o_vakcinaciji" type="saglasnost:TEvidencija">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TDrzavljanstvo">
        <xs:choice>
            <xs:element name="JMBG">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:sequence>
                <xs:element name="Naziv_stranog_drzavljanstva" type="xs:string"/>
                <xs:choice>
                    <xs:element name="Broj_pasosa" type="xs:string"/>
                    <xs:element name="EBS" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TLice">
        <xs:sequence>
            <xs:element name="Drzavljanstvo" type="saglasnost:TDrzavljanstvo"/>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element name="Ime_roditelja" type="xs:string"/>
            <xs:element name="Pol">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="M"/>
                        <xs:element name="Z"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="Datum_rodjenja" type="xs:date"/>
            <xs:element name="Mesto_rodjenja" type="xs:string"/>
            <xs:element name="Adresa" type="saglasnost:TAdresa"> </xs:element>
            <xs:element name="Kontakt">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="Fiksni_telefon">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="([0-9]+)?"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="Mobilni_telefon">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="(06)[0-9]+"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="Imejl">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[a-zA-Z0-9\.]+@[a-zA-Z\.]+.[a-zA-Z]+"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="Radni_status">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="Zaposlen">
                            <xs:complexType>
                                <xs:choice>
                                    <xs:element name="Zdravstvena_zastita"/>
                                    <xs:element name="Socijalna_zastita"/>
                                    <xs:element name="Prosveta"/>
                                    <xs:element name="MUP"/>
                                    <xs:element name="Vojska_RS"/>
                                    <xs:element name="Drugo"/>
                                </xs:choice>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="Nezaposlen"/>
                        <xs:element name="Penzioner"/>
                        <xs:element name="Ucenik"/>
                        <xs:element name="Student"/>
                        <xs:element name="Dete"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:choice>
                <xs:element name="Korisnik_ustanove_socijalne_zasttite" minOccurs="0">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Sediste">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="Naziv" type="xs:string"/>
                                        <xs:element name="Opstina" type="xs:string"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:choice minOccurs="1">
                <xs:element name="Saglasnost" minOccurs="0">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Naziv_imunoloskog_leka" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="Opstina" type="xs:string"/>
            <xs:element name="Naselje" type="xs:string"/>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]+(/[0-9]+)?"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TEvidencija">
        <xs:sequence>
            <xs:element name="Zdravstvena_ustanova" type="xs:string"/>
            <xs:element name="Vakcinacijski_punkt" type="xs:string"/>
            <xs:element name="Lekar">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Ime" type="xs:string"/>
                        <xs:element name="Prezime" type="xs:string"/>
                        <xs:element name="Broj_telefona">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\+?[0-9]+"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Vakcine">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="Vakcina" maxOccurs="unbounded" minOccurs="0"
                            type="saglasnost:TVakcina"> </xs:element>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="Privremene_kontraindikacije">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="Privremena_kontraindikacija" maxOccurs="unbounded"
                            minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Datum_utvrdjivanja" type="xs:date"/>
                                    <xs:element name="Dijagnoza" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:choice>
                <xs:element name="Trajne_kontraindikacije" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVakcina">
        <xs:sequence>
            <xs:element name="Naziv" type="xs:string"/>
            <xs:element name="Datum_davanja" type="xs:date"/>
            <xs:element name="Nacin_davanja" type="xs:string"/>
            <xs:element name="Ekstremitet">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="DR"/>
                        <xs:element name="LR"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="Serija" type="xs:string"/>
            <xs:element name="Proizvodjac" type="xs:string"/>
            <xs:element name="Nezeljena_reakcija" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== djordjee55/xml-veb-servisi/src/main/resources/static/xml/saglasnost.xml
<?xml version="1.0" encoding="UTF-8"?>
<Saglasnost xmlns="http://www.xws.org/saglasnost"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xws.org/saglasnost ../xsd/saglasnost.xsd">
    <Pacijent>
        <Ime xmlns="http://www.xws.org/tipovi">Njegos</Ime>
        <Prezime xmlns="http://www.xws.org/tipovi">Blagojevic</Prezime>
        <Datum_rodjenja xmlns="http://www.xws.org/tipovi">1999-04-29</Datum_rodjenja>
        <Drzavljanstvo><JMBG>2904999183925</JMBG></Drzavljanstvo>
        <Ime_roditelja></Ime_roditelja>
        <Pol>M</Pol>
        <Mesto_rodjenja>Zvornik</Mesto_rodjenja>
        <Adresa>
            <Opstina>Zvornik</Opstina>
            <Naselje>Zvornik</Naselje>
            <Ulica>Svetog Save</Ulica>
            <Broj>12</Broj>
        </Adresa>
        <Kontakt>
            <E_mail xmlns="http://www.xws.org/tipovi">blagojevic.njegos1999@gmail.com</E_mail>
            <Mobilni_telefon xmlns="http://www.xws.org/tipovi">0644790823</Mobilni_telefon>
            <Fiksni_telefon xmlns="http://www.xws.org/tipovi"></Fiksni_telefon>
        </Kontakt>
        <Radni_status><Student></Student></Radni_status>
        <Korisnik_ustanove_socijalne_zasttite>
            <Sediste>
                <Naziv></Naziv>
                <Opstina></Opstina>
            </Sediste>
        </Korisnik_ustanove_socijalne_zasttite>
        <Saglasnost>
            <Naziv_imunoloskog_leka>Pfizer</Naziv_imunoloskog_leka>
        </Saglasnost>
    </Pacijent>
    <Datum>2021-12-12</Datum>
    <Evidencija_o_vakcinaciji>
        <Zdravstvena_ustanova>Zvezdara</Zdravstvena_ustanova>
        <Vakcinacijski_punkt>123</Vakcinacijski_punkt>
        <Lekar>
            <Ime>Pera</Ime>
            <Prezime>Peric</Prezime>
            <Broj_telefona>064412385</Broj_telefona>
        </Lekar>
        <Vakcine>
            <Vakcina>
                <Naziv>Pfizer</Naziv>
                <Datum_davanja>2021-12-20</Datum_davanja>
                <Nacin_davanja></Nacin_davanja>
                <Ekstremitet><DR></DR></Ekstremitet>
                <Serija></Serija>
                <Proizvodjac></Proizvodjac>
                <Nezeljena_reakcija></Nezeljena_reakcija>
            </Vakcina>
        </Vakcine>
        <Privremene_kontraindikacije>
            <Privremena_kontraindikacija>
                <Datum_utvrdjivanja>2021-12-12</Datum_utvrdjivanja>
                <Dijagnoza></Dijagnoza>
            </Privremena_kontraindikacija>
        </Privremene_kontraindikacije>
        <Trajne_kontraindikacije></Trajne_kontraindikacije>
    </Evidencija_o_vakcinaciji>
</Saglasnost>

=== djordjee55/xml-veb-servisi/vaccination-portal/src/main/resources/static/xml/saglasnost.xml
<?xml version="1.0" encoding="UTF-8"?>
<Saglasnost  xmlns:tip="http://www.xws.org/tipovi"
             xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
             xmlns="http://www.xws.org/saglasnost"
             xmlns:pred="http://www.xws.org/predicate"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.xws.org/saglasnost file:../xsd/saglasnost.xsd"
             id="d68ae50a-7cca-4684-9500-f2ea908013f3"
             about="http://www.xws.org/saglasnost#d68ae50a-7cca-4684-9500-f2ea908013f3">
    <Datum property="pred:datumIzdavanja" datatype="xs:date">2006-05-04</Datum>
    <Pacijent>
        <tip:Ime>Ime0</tip:Ime>
        <tip:Prezime>Prezime0</tip:Prezime>
        <tip:Datum_rodjenja>2006-05-04</tip:Datum_rodjenja>
        <Drzavljanstvo>
            <Naziv_stranog_drzavljanstva>Naziv_stranog_drzavljanstva0</Naziv_stranog_drzavljanstva>
            <Broj_pasosa rel="pred:identifikatorKorisnika" href="http://www.xws.org/korisnici#921909aa-8ff1-47f4-b761-4cbac06929ad">Broj_pasosa0</Broj_pasosa>
        </Drzavljanstvo>
        <Ime_roditelja>Ime_roditelja0</Ime_roditelja>
        <Pol>M</Pol>
        <Mesto_rodjenja>Mesto_rodjenja0</Mesto_rodjenja>
        <Adresa>
            <Opstina>Opstina0</Opstina>
            <Naselje>Naselje0</Naselje>
            <Ulica>Ulica0</Ulica>
            <Broj>0</Broj>
        </Adresa>
        <Kontakt>
            <tip:E_mail>djordjenjegic@email.com</tip:E_mail>
            <tip:Fiksni_telefon>023456789</tip:Fiksni_telefon>
            <tip:Mobilni_telefon>060123456789</tip:Mobilni_telefon>
        </Kontakt>
        <Radni_status>
            <Penzioner>
            </Penzioner>
        </Radni_status>
        <Korisnik_ustanove_socijalne_zasttite>
            <Sediste>
                <Naziv></Naziv>
                <Opstina></Opstina>
            </Sediste>
        </Korisnik_ustanove_socijalne_zasttite>
        <Saglasnost>
            <Naziv_imunoloskog_leka>neki naziv</Naziv_imunoloskog_leka>
        </Saglasnost>
    </Pacijent>
    <Evidencija_o_vakcinaciji>
        <Zdravstvena_ustanova>Zdravstvena_ustanova0</Zdravstvena_ustanova>
        <Vakcinacijski_punkt>Vakcinacijski_punkt0</Vakcinacijski_punkt>
        <Lekar>
            <Ime>Ime0</Ime>
            <Prezime>Prezime0</Prezime>
            <Broj_telefona>0</Broj_telefona>
        </Lekar>
        <Vakcine>
            <Vakcina>
                <Naziv>naziv vakcine</Naziv>
                <Datum_davanja>neki datum</Datum_davanja>
                <Nacin_davanja>neki nacin</Nacin_davanja>
                <Ekstremitet>
                    <LR></LR>
                </Ekstremitet>
                <Serija>neka serija</Serija>
                <Proizvodjac>neki proizvodjac</Proizvodjac>
                <Nezeljena_reakcija></Nezeljena_reakcija>
            </Vakcina>
        </Vakcine>
        <Privremene_kontraindikacije>
            <Privremena_kontraindikacija>
                <Datum_utvrdjivanja>datum1</Datum_utvrdjivanja>
                <Dijagnoza>nesto1</Dijagnoza>
            </Privremena_kontraindikacija>
            <Privremena_kontraindikacija>
                <Datum_utvrdjivanja>datum2</Datum_utvrdjivanja>
                <Dijagnoza>nesto2</Dijagnoza>
            </Privremena_kontraindikacija>
        </Privremene_kontraindikacije>
        <Trajne_kontraindikacije></Trajne_kontraindikacije>
    </Evidencija_o_vakcinaciji>
</Saglasnost>
