=== djordjee55/xml-veb-servisi/KT2/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="htttp://www.xws.org/zahtev"
    xmlns:zahtev="htttp://www.xws.org/zahtev">

    <xs:element name="Zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podnosilac" type="zahtev:TLice"/>
                <xs:element name="Razlog" type="xs:string" nillable="false"/>
                <xs:element name="Mesto" type="xs:string"/>
                <xs:element name="Datum" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TLice">
        <xs:sequence>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element name="Datum_rodjenja" type="xs:date"/>
            <xs:element name="Pol" type="xs:string"/>
            <xs:element name="JMBG">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="13"/>
                        <xs:pattern value="[0-9]{13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Broj_pasosa" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== djordjee55/xml-veb-servisi/KT2/instanca_zahteva.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev xmlns="htttp://www.xws.org/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="htttp://www.xws.org/zahtev zahtev.xsd">
    <Podnosilac>
        <Ime>Marko</Ime>
        <Prezime>Marković</Prezime>
        <Datum_rodjenja>1987-05-25</Datum_rodjenja>
        <Pol>Muško</Pol>
        <JMBG>2339472340742</JMBG>
        <Broj_pasosa>123432</Broj_pasosa>
    </Podnosilac>
    <Razlog>Neki razlog</Razlog>
    <Mesto>Novi Sad</Mesto>
    <Datum>2021-08-20</Datum>
</Zahtev>

=== djordjee55/xml-veb-servisi/vaccination-main/src/main/resources/static/xml/zahtev.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev:Zahtev xmlns:zahtev="http://www.xws.org/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xws.org/zahtev ../xsd/zahtev.xsd">
    <zahtev:Podnosilac>
        <Ime xmlns="http://www.xws.org/tipovi">Njegos</Ime>
        <Prezime xmlns="http://www.xws.org/tipovi">Blagojevic</Prezime>
        <Datum_rodjenja xmlns="http://www.xws.org/tipovi">1999-04-29</Datum_rodjenja>
        <Pol xmlns="http://www.xws.org/tipovi">M</Pol>
        <JMBG xmlns="http://www.xws.org/tipovi">2904999183925</JMBG>
        <Broj_pasosa xmlns="http://www.xws.org/tipovi"></Broj_pasosa>
    </zahtev:Podnosilac>
    <zahtev:Razlog></zahtev:Razlog>
    <zahtev:Mesto></zahtev:Mesto>
    <zahtev:Datum>2021-12-20</zahtev:Datum>
</zahtev:Zahtev>

=== djordjee55/xml-veb-servisi/vaccination-portal/src/main/resources/static/xml/zahtev.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
         xmlns="http://www.xws.org/zahtev"
         xmlns:tip="http://www.xws.org/tipovi"
         xmlns:pred="http://www.xws.org/predicate"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.xws.org/zahtev file:../xsd/zahtev.xsd"
         id="bda26206-5c66-4771-a038-cee3a4600c02"
         about="http://www.xws.org/zahtev#bda26206-5c66-4771-a038-cee3a4600c02">
    <Datum property="pred:datumIzdavanja" datatype="xs:date">2006-05-04</Datum>
    <Podnosilac>
        <tip:Ime>Ime0</tip:Ime>
        <tip:Prezime>Prezime0</tip:Prezime>
        <tip:Datum_rodjenja>2006-05-04</tip:Datum_rodjenja>
        <tip:Pol>M</tip:Pol>
        <tip:JMBG rel="pred:identifikatorKorisnika" href="http://www.xws.org/korisnici#921909aa-8ff1-47f4-b761-4cbac06929ad">0000000000000</tip:JMBG>
        <tip:Broj_pasosa rel="pred:identifikatorKorisnika" href="http://www.xws.org/korisnici#921909aa-8ff1-47f4-b761-4cbac06929ad">Broj_pasosa0</tip:Broj_pasosa>
    </Podnosilac>
    <Razlog>Razlog0</Razlog>
    <Mesto>Mesto0</Mesto>
</Zahtev>
