=== djordjee55/xml-veb-servisi/vaccination-main/src/main/resources/static/xsd/izvestaj.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" targetNamespace="http://www.xws.org/izvestaj"
    xmlns:izvestaj="http://www.xws.org/izvestaj" xmlns:tip="http://www.xws.org/tipovi"
    xmlns:pred="http://www.xws.org/predicate">

    <xs:import namespace="http://www.xws.org/tipovi" schemaLocation="tipovi.xsd"/>

    <xs:element name="Izvestaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Datum_izdavanja" type="xs:date"/>
                <xs:element name="Period">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Od" type="xs:date"/>
                            <xs:element name="Do" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Broj_podnetih_dokumenata_o_interesovanju"
                    type="xs:nonNegativeInteger"/>
                <xs:element name="Broj_primljenih_zahteva_za_digitalni_zeleni_sertifikat"
                    type="xs:nonNegativeInteger"/>
                <xs:element name="Broj_izdatih_zahteva_za_digitalni_zeleni_sertifikat"
                    type="xs:nonNegativeInteger"/>
                <xs:element name="Ukupan_broj_datih_doza_vakcine" type="xs:nonNegativeInteger"/>
                <xs:element name="Doze">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="Doza">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="1">
                                        <xs:element name="Broj_datih_doza"
                                            type="xs:nonNegativeInteger"/>
                                    </xs:sequence>
                                    <xs:attribute name="redni_broj" type="xs:positiveInteger"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Raspodela_po_proizvodjacima">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="Proizvodjac">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Naziv" type="tip:TVakcina"/>
                                        <xs:element name="Broj_doza" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== djordjee55/xml-veb-servisi/vaccination-main/src/main/resources/static/xml/izvestaj.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj
         xmlns:tip="http://www.xws.org/tipovi"
         xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
         xmlns="http://www.xws.org/izvestaj"
         xmlns:pred="http://www.xws.org/predicate"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.xws.org/izvestaj file:../xsd/izvestaj.xsd"
         id="7faef6a8-297e-4d35-bb77-fa71742b990c">
    <Datum_izdavanja>2006-05-04</Datum_izdavanja>
    <Period>
        <Od>2006-05-04</Od>
        <Do>2006-05-04</Do>
    </Period>
    <Broj_podnetih_dokumenata_o_interesovanju>50</Broj_podnetih_dokumenata_o_interesovanju>
    <Broj_primljenih_zahteva_za_digitalni_zeleni_sertifikat>50</Broj_primljenih_zahteva_za_digitalni_zeleni_sertifikat>
    <Broj_izdatih_zahteva_za_digitalni_zeleni_sertifikat>50</Broj_izdatih_zahteva_za_digitalni_zeleni_sertifikat>
    <Ukupan_broj_datih_doza_vakcine>50</Ukupan_broj_datih_doza_vakcine>
    <Doze>
        <Doza>
            <Broj_datih_doza>50</Broj_datih_doza>
        </Doza>
        <Doza>
            <Broj_datih_doza>50</Broj_datih_doza>
        </Doza>
    </Doze>
    <Raspodela_po_proizvodjacima>
        <Proizvodjac>
            <Naziv>Pfizer-BioNTech</Naziv>
            <Broj_doza>50</Broj_doza>
        </Proizvodjac>
        <Proizvodjac>
            <Naziv>Pfizer-BioNTech</Naziv>
            <Broj_doza>50</Broj_doza>
        </Proizvodjac>
    </Raspodela_po_proizvodjacima>
</Izvestaj>
